import { z } from 'zod';

// ─── Database Entity Types ────────────────────────────────────────────────────
// These represent what the database returns (after mapping column names).
// Used as return types from repositories and API responses.

export interface User {
  id: number;
  name: string;
  email: string;
  createdAt: string; // ISO 8601 string, e.g. "2024-01-01T00:00:00.000Z"
}

// ─── Input Types ──────────────────────────────────────────────────────────────
// What the client sends in the request body.
// Does NOT include id or createdAt — those are generated by the database.

export type CreateUserInput = {
  name: string;
  email: string;
};

// ─── Zod Validation Schemas ───────────────────────────────────────────────────
// TypeScript types are COMPILE-TIME only — they vanish at runtime.
// When a JSON request arrives over HTTP, it is completely untyped.
// Zod validates the actual runtime values and returns either a typed object
// or a detailed error — it works alongside TypeScript, not instead of it.

export const CreateUserSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters'),
  email: z.string().email('Must be a valid email address'),
});

// Derive the TypeScript type from the schema so they are always in sync.
// If you add a field to CreateUserSchema, CreateUserSchemaType updates automatically.
export type CreateUserSchemaType = z.infer<typeof CreateUserSchema>;